name: manju
description: A new Flutter project.

# A linha a seguir evita que o pacote seja acidentalmente publicado em
# pub.dev usando `flutter pub publish`. Isso é preferido para pacotes privados.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

# O seguinte define a versão e o número da compilação para seu aplicativo.
# Um número de versão são três números separados por pontos, como 1.2.43
# seguido por um número de compilação opcional separado por um +.
# Tanto a versão quanto o número do construtor podem ser substituídos em flutter
# build especificando --build-name e --build-number, respectivamente.
# No Android, o build-name é usado como versionName, enquanto o build-number é usado como versionCode.
# Leia mais sobre o controle de versão do Android em https://developer.android.com/studio/publish/versioning
# No iOS, build-name é usado como CFBundleShortVersionString, enquanto o build-number é usado como CFBundleVersion.
# Leia mais sobre o controle de versão do iOS em
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-262.0.dev <3.0.0"

# Dependências especificam outros pacotes de que seu pacote precisa para funcionar.
# Para atualizar automaticamente as dependências do seu pacote para as versões mais recentes
# considere executar `flutter pub upgrade --major-versions`. Alternativamente,
# dependências podem ser atualizadas manualmente alterando os números de versão abaixo para
# a versão mais recente disponível em pub.dev. Para ver quais dependências têm mais
# versões disponíveis, execute `flutter pub outdated`.
dependencies:
  provider: ^6.0.1
  get: ^4.3.8
  flutter:
    sdk: flutter


  # O seguinte adiciona a fonte Cupertino Icons ao seu aplicativo.
  # Use com a classe CupertinoIcons para ícones de estilo iOS.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # O pacote "flutter_lints" abaixo contém um conjunto de lints recomendados para
  # encorajar boas práticas de codificação. O conjunto de fiapos fornecido pelo pacote é
  # ativado no arquivo `analysis_options.yaml` localizado na raiz do seu
  # pacote. Consulte esse arquivo para obter informações sobre como desativar lint específico
  # regras e ativando outras adicionais.
  flutter_lints: ^1.0.0

# Para obter informações sobre a parte genérica do DART deste arquivo, consulte o
# página seguinte: https://dart.dev/tools/pub/pubspec

# A seção a seguir é específica para Flutter.
flutter:

# A linha a seguir garante que a fonte Material Icons seja
  # incluído em seu aplicativo, para que você possa usar os ícones em
  # a classe de ícones de materiais.
  uses-material-design: true

# Para adicionar ativos ao seu aplicativo, adicione uma seção de ativos, como esta:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # Um ativo de imagem pode se referir a uma ou mais "variantes" específicas de resolução, consulte
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # Para adicionar fontes personalizadas ao seu aplicativo, adicione uma seção de fontes aqui,
  # nesta seção "vibração". Cada entrada nesta lista deve ter um
  # tecla "family" com o nome da família da fonte e uma tecla "fonts" com um
  # lista fornecendo o recurso e outros descritores para a fonte. Para
  # exemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para obter detalhes sobre fontes de dependências de pacote,
  # consulte https://flutter.dev/custom-fonts/#from-packages
